
{
    "background-color":"0xffe4c4ff",
    "Shapes":[
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":530.0,
                "y-location":188.0
            },
            "Dimensions":{
                "width":506.0,
                "height":300.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":948.0,
                "y-location":265.0
            },
            "Dimensions":{
                "width":484.0,
                "height":287.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":702.0,
                "y-location":299.0
            },
            "Dimensions":{
                "width":460.0,
                "height":283.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        }
    ]
}