
{
    "Background-Color":"0xffe4c4ff",
    "Shapes":[
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":1268.0,
                "y-location":121.0
            },
            "Dimensions":{
                "width":163.0,
                "height":172.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":399.0,
                "y-location":159.0
            },
            "Dimensions":{
                "width":261.0,
                "height":251.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Ellipse",
            "Coordinates":{
                "x-location":881.0,
                "y-location":305.0
            },
            "Dimensions":{
                "width":97.0,
                "height":119.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":213.0,
                "y-location":604.0
            },
            "Dimensions":{
                "width":591.0,
                "height":139.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        }
    ]
}