
{
    "background-color":"0x1a0068ff",
    "Shapes":[
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":288.0,
                "y-location":767.0
            },
            "Dimensions":{
                "width":168.0,
                "height":120.0
            },
            "fill-color":"0xcce6ffff",
            "border-color":"0x4d66ccff",
            "border-width":11.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":136.0,
                "y-location":103.0
            },
            "Dimensions":{
                "width":440.0,
                "height":254.0
            },
            "fill-color":"0xe6e680ff",
            "border-color":"0x334db3ff",
            "border-width":20.0
        },
        {
            "Type":"Ellipse",
            "Coordinates":{
                "x-location":1101.0,
                "y-location":332.0
            },
            "Dimensions":{
                "width":71.0,
                "height":106.0
            },
            "fill-color":"0x990000ff",
            "border-color":"0xcc8099ff",
            "border-width":8.09090909090909
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":1164.0,
                "y-location":231.0
            },
            "Dimensions":{
                "width":-10.0,
                "height":244.0
            },
            "fill-color":"0xff6666ff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Ellipse",
            "Coordinates":{
                "x-location":486.0,
                "y-location":574.0
            },
            "Dimensions":{
                "width":106.0,
                "height":114.0
            },
            "fill-color":"0x1a3399ff",
            "border-color":"0x000000ff",
            "border-width":20.0
        },
        {
            "Type":"Ellipse",
            "Coordinates":{
                "x-location":141.0,
                "y-location":578.0
            },
            "Dimensions":{
                "width":76.0,
                "height":83.0
            },
            "fill-color":"0x4d1a4dff",
            "border-color":"0xccffffff",
            "border-width":9.272727272727273
        },
        {
            "Type":"Ellipse",
            "Coordinates":{
                "x-location":1049.0,
                "y-location":782.0
            },
            "Dimensions":{
                "width":86.0,
                "height":85.0
            },
            "fill-color":"0xffccffff",
            "border-color":"0x99cc99ff",
            "border-width":5.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":672.0,
                "y-location":233.0
            },
            "Dimensions":{
                "width":273.0,
                "height":239.0
            },
            "fill-color":"0x804d80ff",
            "border-color":"0xcc3333ff",
            "border-width":5.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":1318.0,
                "y-location":709.0
            },
            "Dimensions":{
                "width":206.0,
                "height":139.0
            },
            "fill-color":"0x999933ff",
            "border-color":"0xb34d1aff",
            "border-width":20.0
        },
        {
            "Type":"Rectangle",
            "Coordinates":{
                "x-location":1351.0,
                "y-location":150.0
            },
            "Dimensions":{
                "width":200.0,
                "height":360.0
            },
            "fill-color":"0xb3e6b3ff",
            "border-color":"0x1a4d1aff",
            "border-width":20.0
        }
    ]
}